# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = '50GB'
  config.vm.define "linuxsvc" do |d|
    d.vm.hostname = "linuxsvc"
    d.vm.network "private_network", ip: "192.168.0.5"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/linuxsvc.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "cd" do |d|
    d.vm.hostname = "cd"
    d.vm.network "private_network", ip: "192.168.0.6"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/cd.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 2048
      v.cpus = 2
    end
  end
    config.vm.define "hdp" do |d|
    d.vm.hostname = "hdp"
    d.vm.network "private_network", ip: "192.168.0.7"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provision :shell, inline: "PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/hdp.yml -c local"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 2048
      v.cpus = 2
    end
  end
  config.vm.define "dlowkeyvmaa" do |d|
    d.vm.hostname = "dlowkeyvmaa"
    d.vm.network "public_network"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 1024 
      v.cpus = 1
    end
  end
  config.vm.define "dlowkeyvmab" do |d|
    d.vm.hostname = "dlowkeyvmab"
    d.vm.network "public_network"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 1024
      v.cpus = 1
    end
  end
  config.vm.define "dlowkeyvmac" do |d|
    d.vm.hostname = "dlowkeyvmac"
    d.vm.network "public_network"
    d.vm.provision :shell, path: "scripts/bootstrap_ansible.sh"
    d.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.memory = 1024
      v.cpus = 1
    end
  end
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
    config.vbguest.no_install = true
    config.vbguest.no_remote = true
  end
end
