- name: JQ is present
  apt:
    name: jq
    force: yes
  tags: [common]

- name: Host is present
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item.host_ip }}"
    line: "{{ item.host_ip }} {{ item.host_name }}"
  with_items: "{{ hosts }}"
  tags: [common]
  
- name: 
  lineinfile:
    dest: /etc/hosts
    state: absent
    regexp: '^127\.0\.1\.1'
  tags: [common]
  


