- name: add apt key docker
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    state: 'present'

#- name: add apt signing key for azure cli from url
#  apt_key:
#    url: https://packages.microsoft.com/keys/microsoft.asc
#    state: present

- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    update_cache: yes
    state: present
  tags: [docker]

- name: Debian Docker is present
  apt:
    name: docker-ce=18.06.0~ce~3-0~ubuntu
    update_cache: yes
#    state: present
  tags: [docker]

- name: Reload systemd daemon
  systemd:
    daemon_reload: true

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  tags: [docker]

- name: Debian Docker service is restarted
  service:
    name: docker
    state: restarted
  tags: [docker]
 
