- name: add apt key docker
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    state: 'present'

- name: Debian add Docker repository and update apt cache
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    update_cache: yes
    state: present
  tags: [docker]

- name: Debian Docker is present
  apt:
#name: docker-ce=18.06.0~ce~3-0~ubuntu
    name: docker-ce
    update_cache: yes
    state: present
  tags: [docker]

- name: docker-compose is present
  apt:
    name: docker-compose
    update_cache: yes
    state: present
  tags: [docker]


- name: 'enable docker systemd service'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'

- name: ossist user is added to the docker group
  user:
    name: ossist
    group: docker
  tags: [docker]
  
 - name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  tags: [docker]


